export enum EquipmentEnum {
  DUMBBELL = "DUMBBELL",
  BARBELL = "BARBELL",
  BODYWEIGHT = "BODYWEIGHT",
  CABLE = "CABLE",
  MACHINE = "MACHINE",
  EZ_BAR = "EZ_BAR",
  BODYWEIGHT_LOADABLE = "BODYWEIGHT_LOADABLE",
  ASSISTED_MACHINE = "ASSISTED_MACHINE",
}
